alias cdc="cd && clear"
alias tmux="TERM=screen-256color-bce tmux"
alias myip="curl ifconfig.me"
alias s="screen"
alias t="tmux"
alias tt="tmux attach -t"
alias tl="if tmux has; then tmux attach; else tmux new; fi"
alias c="clear"
alias g="git"
alias gsu="git submodule init && git submodule update"
alias gfv="git fetch origin -v; git fetch upstream -v"

